<a href="https://colab.research.google.com/github/chaymae255/TechnovationProjectApp/blob/main/aigooglecolab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("tea340yashjoshi/skill-and-career-recommendation-dataset")

print("Path to dataset files:", path)

100%|██████████| 497k/497k [00:00<00:00, 72.6MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/tea340yashjoshi/skill-and-career-recommendation-dataset/versions/1


In [ ]:
import pandas as pd

# Provide the path to the uploaded file (e.g., 'your_file.xls')
file_path = '/content/dataset.xlsx'

# Read the Excel file
data = pd.read_excel(file_path)

# Show the first few rows to verify
data.head()

Sr.No.  Course Job profession Student  Linguistic  Musical  Bodily  \
0     1.0     NaN   Astronomer\n      S1          11        5      12   
1     NaN     NaN   Astronomer\n      S2          12        6      12   
2     NaN     NaN   Astronomer\n      S3          13        7      12   
3     NaN     NaN   Astronomer\n      S4          14        8      12   
4     NaN     NaN   Astronomer\n      S5          13        9      12   

   Logical - Mathematical  Spatial-Visualization  Interpersonal  ...  \
0                      16                     17             11  ...   
1                      16                     16             11  ...   
2                      16                     15             11  ...   
3                      16                     19             11  ...   
4                      16                     20             11  ...   

   Naturalist  s/p   P1    P2   P3    P4    P5   P6    P7    P8  
0          19   s1  AVG  POOR  AVG  BEST  BEST  AVG  BEST  BEST  
1          19   s2  AVG  POOR  AVG  BEST  BEST  AVG  BEST  BEST  
2          19   s3  AVG  POOR  AVG  BEST  BEST  AVG  BEST  BEST  
3          19   s4  AVG  POOR  AVG  BEST  BEST  AVG  BEST  BEST  
4          19   s5  AVG  POOR  AVG  BEST  BEST  AVG  BEST  BEST  

[5 rows x 21 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Sr.No.                  72 non-null     float64
 1   Course                  0 non-null      float64
 2   Job profession          3600 non-null   object 
 3   Student                 3600 non-null   object 
 4   Linguistic              3600 non-null   int64  
 5   Musical                 3600 non-null   int64  
 6   Bodily                  3600 non-null   int64  
 7   Logical - Mathematical  3600 non-null   int64  
 8   Spatial-Visualization   3600 non-null   int64  
 9   Interpersonal           3600 non-null   int64  
 10  Intrapersonal           3600 non-null   int64  
 11  Naturalist              3600 non-null   int64  
 12  s/p                     3600 non-null   object 
 13  P1                      3600 non-null   object 
 14  P2                      3600 non-null   

In [ ]:
data = data.drop(columns=['Course', 'Sr.No.'])
data = data.drop(columns=['Student'])

In [ ]:
print(data['Job profession'].isnull().sum())

0


In [ ]:
print(data['Linguistic'].isnull().sum())

In [ ]:
print(data['Musical'].isnull().sum())

0


In [ ]:
print(data['Bodily'].isnull().sum())

0


In [ ]:
print(data['Logical - Mathematical'].isnull().sum())


In [ ]:
print(data['Spatial-Visualization'].isnull().sum())


0


In [ ]:
print(data['Interpersonal'].isnull().sum())


0


In [ ]:
print(data['Naturalist'].isnull().sum())


0


In [ ]:
data = data.drop(columns=['s/p'])

In [ ]:
data.head()

Job profession Student  Linguistic  Musical  Bodily  Logical - Mathematical  \
0   Astronomer\n      S1          11        5      12                      16   
1   Astronomer\n      S2          12        6      12                      16   
2   Astronomer\n      S3          13        7      12                      16   
3   Astronomer\n      S4          14        8      12                      16   
4   Astronomer\n      S5          13        9      12                      16   

   Spatial-Visualization  Interpersonal  Intrapersonal  Naturalist   P1    P2  \
0                     17             11             18          19  AVG  POOR   
1                     16             11             18          19  AVG  POOR   
2                     15             11             18          19  AVG  POOR   
3                     19             11             18          19  AVG  POOR   
4                     20             11             19          19  AVG  POOR   

    P3    P4    P5   P6    P7    P8  
0  AVG  BEST  BEST  AVG  BEST  BEST  
1  AVG  BEST  BEST  AVG  BEST  BEST  
2  AVG  BEST  BEST  AVG  BEST  BEST  
3  AVG  BEST  BEST  AVG  BEST  BEST  
4  AVG  BEST  BEST  AVG  BEST  BEST

In [ ]:
data = data.drop(columns=['P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8'])

In [ ]:
data.head()

Job profession  Linguistic  Musical  Bodily  Logical - Mathematical  \
0   Astronomer\n          11        5      12                      16   
1   Astronomer\n          12        6      12                      16   
2   Astronomer\n          13        7      12                      16   
3   Astronomer\n          14        8      12                      16   
4   Astronomer\n          13        9      12                      16   

   Spatial-Visualization  Interpersonal  Intrapersonal  Naturalist  
0                     17             11             18          19  
1                     16             11             18          19  
2                     15             11             18          19  
3                     19             11             18          19  
4                     20             11             19          19

In [ ]:
# Features (all columns except 'Job profession')
X = data.drop('Job profession', axis=1)

# Target (only 'Job profession')
y = data['Job profession']

In [ ]:
print(X)

      Linguistic  Musical  Bodily  Logical - Mathematical  \
0             11        5      12                      16   
1             12        6      12                      16   
2             13        7      12                      16   
3             14        8      12                      16   
4             13        9      12                      16   
...          ...      ...     ...                     ...   
3595           8        7      15                      12   
3596           9        8      16                      11   
3597          10        8      17                      12   
3598           6        9      19                      13   
3599           8        9      18                      14   

      Spatial-Visualization  Interpersonal  Intrapersonal  Naturalist  
0                        17             11             18          19  
1                        16             11             18          19  
2                        15             11         

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Create a label encoder object
le = LabelEncoder()

# Fit the encoder and transform the target variable
y_encoded = le.fit_transform(y)

# Now y_encoded is numeric!


In [ ]:
print(y_encoded)


[ 5  5  5 ... 69 69 69]


In [ ]:
import numpy as np

# Show unique labels and their count
unique_labels, counts = np.unique(y_encoded, return_counts=True)
print(f"Unique labels: {unique_labels}")
print(f"Counts: {counts}")

Unique labels: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71]
Counts: [50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50
 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50 50]


In [ ]:
from sklearn.model_selection import train_test_split

# Step 2: Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Check the shape of the resulting datasets (optional)
print(f"Training feature set shape: {X_train.shape}")
print(f"Test feature set shape: {X_test.shape}")
print(f"Training target set shape: {y_train.shape}")
print(f"Test target set shape: {y_test.shape}")

Training feature set shape: (2880, 8)
Test feature set shape: (720, 8)
Training target set shape: (2880,)
Test target set shape: (720,)


In [ ]:
print(X_train)

      Linguistic  Musical  Bodily  Logical - Mathematical  \
3281          13        9       8                      19   
2383          15       14       8                      17   
2009          13       18      12                       9   
2114           6        8      14                      13   
1128          14        8      14                      18   
...          ...      ...     ...                     ...   
1130          11       10      12                      18   
1294          14        7      15                       9   
860           16        5      11                      19   
3507           6        6      18                      19   
3174          16       20      20                      14   

      Spatial-Visualization  Interpersonal  Intrapersonal  Naturalist  
3281                     16              9             19          13  
2383                      6             14             17          14  
2009                      5             12         

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)


In [ ]:
rf_model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Job profession          3600 non-null   object
 1   Linguistic              3600 non-null   int64 
 2   Musical                 3600 non-null   int64 
 3   Bodily                  3600 non-null   int64 
 4   Logical - Mathematical  3600 non-null   int64 
 5   Spatial-Visualization   3600 non-null   int64 
 6   Interpersonal           3600 non-null   int64 
 7   Intrapersonal           3600 non-null   int64 
 8   Naturalist              3600 non-null   int64 
dtypes: int64(8), object(1)
memory usage: 253.3+ KB


In [ ]:
# Make predictions on the test set
y_pred = rf_model.predict(X_test)


In [ ]:
from sklearn.metrics import accuracy_score

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')


Accuracy: 97.08%


In [ ]:
from sklearn.metrics import confusion_matrix

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)


Confusion Matrix:
[[14  0  0 ...  0  0  0]
 [ 0  9  0 ...  0  0  0]
 [ 0  0  8 ...  0  0  0]
 ...
 [ 0  0  0 ... 10  0  0]
 [ 0  0  0 ...  0 16  0]
 [ 0  0  0 ...  0  0  9]]


In [ ]:
from sklearn.metrics import classification_report

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)


Classification Report:
                                                                                                precision    recall  f1-score   support

                                                                               Actor / Actress       1.00      1.00      1.00        14
                                                                                       Actuary       1.00      1.00      1.00         9
                                                                                Anthropologist       1.00      1.00      1.00         8
                                                                                  Archeologist       1.00      1.00      1.00         6
                                                                                        Artist       1.00      1.00      1.00         7
                                                                                   Astronomer
       1.00      1.00      1.00        12
                        

In [ ]:
import joblib

# Save the trained model to a file
joblib.dump(rf_model, 'random_forest_model.pkl')


['random_forest_model.pkl']

In [ ]:
joblib.dump(le, 'label_encoder.pkl')


['label_encoder.pkl']